package agent

import (
	"bytes"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/PillowPillow/den/internal/nest"
	"github.com/PillowPillow/den/internal/sbx"
	"gopkg.in/yaml.v3"
)

// mixinVersion is fixed: the mixin is regenerated on every `sbx create` and has
// no lifecycle of its own. A variable version would only make golden files
// diverge for nothing.
const mixinVersion = "0.0.0"

// Mixin is the disposable kit den generates on every spawn (spec §6.5).
type Mixin struct {
	SandboxName string
	Env         map[string]string // already merged and substituted by nest.Resolve
	Egress      []string          // already unioned and sorted by nest.Resolve
	Freshness   []string          // argv, see FreshnessCommand
	// Links is the argv of the link phase, or nil when nothing needs linking.
	// Emitted as the FIRST setup.startup entry — see LinkCommand for why it
	// cannot go after Freshness.
	Links []string
}

// MixinFrom assembles the mixin of a resolved nest.
//
// Env and Egress are COPIED: they are exported fields of an exported struct,
// and aliasing them would turn a write on the mixin into a silent mutation of
// the resolved nest, which the caller keeps using after the spawn.
func MixinFrom(r *nest.Resolved, sandboxName string) (Mixin, error) {
	freshness, err := FreshnessCommand(r.AgentName, r.Agent)
	if err != nil {
		return Mixin{}, err
	}
	return Mixin{
		SandboxName: sandboxName,
		Env:         maps.Clone(r.Env),
		Egress:      slices.Clone(r.Egress),
		Freshness:   freshness,
		Links:       LinkCommand(r.Mounts),
	}, nil
}

// RenderMixin serializes the mixin to the real sbx schema (schemaVersion 2).
//
// The YAML is built node by node rather than via yaml.Marshal of a map: Go
// map iteration order is random, and a golden file cannot tolerate that.
// environment.variables keys are emitted SORTED.
func RenderMixin(m Mixin) ([]byte, error) {
	// Freshness does NOT follow the empty-section rule: omitting it would
	// render a perfectly valid mixin that starts a sandbox with no freshness
	// check at all — a silent fail-OPEN, exactly what FreshnessCommand refuses
	// for an agent without an update command (spec §9.1). MixinFrom can never
	// reach this case, but RenderMixin is exported and Mixin is a bare struct.
	if len(m.Freshness) == 0 {
		return nil, fmt.Errorf(
			"rendering mixin for %s: no freshness command — a sandbox must never "+
				"start with a stale agent", m.SandboxName)
	}

	root := &yaml.Node{Kind: yaml.MappingNode}

	add := func(key string, value *yaml.Node) {
		root.Content = append(root.Content, scalarNode(key), value)
	}

	add("schemaVersion", scalarNode("2"))
	add("kind", scalarNode("mixin"))
	// MixinName owns the flattening, because the same string is what identifies
	// den's own lines in the kit dispatcher's journal (gate.go): two spellings
	// of it would make the §9.1 gate silently watch a kit nobody generated.
	add("name", scalarNode(MixinName(m.SandboxName)))
	add("version", scalarNode(mixinVersion))
	add("description", scalarNode(fmt.Sprintf(
		"Mixin generated by den for sandbox %s. Regenerated on every spawn, "+
			"do not edit by hand.", m.SandboxName)))

	// Sections are omitted when empty: an empty `allow: []` would mean
	// "nothing allowed", not "no constraint".
	//
	// `permissions.network.allow`, not `caps.network.allow`: sbx renamed the
	// section between v0.35 and v0.38 (measured 2026-08-10 — `sbx kit validate`
	// answers `field caps not found in type spec.permissionsBlockV2`). The old
	// spelling is now a HARD refusal at `sbx create`, before any VM exists, so
	// den emits the new one only. ReadMixin still understands both — the mixins
	// already cached on a machine were written with the old keys, and they are
	// the drift reference of the sandboxes still running.
	if len(m.Egress) > 0 {
		network := &yaml.Node{Kind: yaml.MappingNode}
		network.Content = append(network.Content, scalarNode("allow"), sequenceNode(m.Egress))
		permissions := &yaml.Node{Kind: yaml.MappingNode}
		permissions.Content = append(permissions.Content, scalarNode("network"), network)
		add("permissions", permissions)
	}

	if len(m.Env) > 0 {
		vars := &yaml.Node{Kind: yaml.MappingNode}
		for _, k := range slices.Sorted(maps.Keys(m.Env)) {
			// BOTH key and value are user data. The key comes from a nest's or
			// agent's `env:`, and no charset validation applies anywhere in the
			// cascade. A null key is worse than a null value — it drops the
			// WHOLE entry on reread, not just its right-hand side.
			vars.Content = append(vars.Content, stringNode(k), stringNode(m.Env[k]))
		}
		env := &yaml.Node{Kind: yaml.MappingNode}
		env.Content = append(env.Content, scalarNode("variables"), vars)
		add("environment", env)
	}

	// startup is a SEQUENCE, and sbx runs EVERY entry, in declared order, each
	// as its own numbered script under /etc/durable-startup.d (measured
	// 2026-08-07 with a two-entry probe kit; before that, no kit anywhere
	// carried more than one entry and the behaviour was unverified). Re-measured
	// 2026-08-10 on sbx v0.38 under the RENAMED `setup.startup` key: same
	// two-entry probe, same declared order. A key rename is not a promise about
	// the runtime, and freshness-runs-LAST is a §9.1 safety invariant.
	//
	// Links first, Freshness LAST. Freshness is unconditional and guaranteed
	// non-empty by the guard at the top of this function; the link entry is
	// omitted when there is nothing to link.
	var entries []*yaml.Node
	if len(m.Links) > 0 {
		linkEntry := &yaml.Node{Kind: yaml.MappingNode}
		linkEntry.Content = append(linkEntry.Content, scalarNode("command"), sequenceNode(m.Links))
		entries = append(entries, linkEntry)
	}
	entry := &yaml.Node{Kind: yaml.MappingNode}
	entry.Content = append(entry.Content, scalarNode("command"), sequenceNode(m.Freshness))
	entries = append(entries, entry)

	startup := &yaml.Node{Kind: yaml.SequenceNode, Content: entries}
	setup := &yaml.Node{Kind: yaml.MappingNode}
	setup.Content = append(setup.Content, scalarNode("startup"), startup)
	// `setup.startup`, not `commands.startup` — same sbx rename as `permissions`
	// above (`field commands not found in type spec.specFileV2`). The entry shape
	// (`- command: [argv...]`) did not move.
	add("setup", setup)

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(root); err != nil {
		return nil, fmt.Errorf("rendering mixin for %s: %w", m.SandboxName, err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("rendering mixin for %s: %w", m.SandboxName, err)
	}
	return buf.Bytes(), nil
}

// scalarNode builds a STRUCTURAL scalar node: keys, and values den sets itself
// (schemaVersion, kind, name, version, description). They are known, and
// `schemaVersion: 2` must stay the number 2.
//
// Multiline content switches to literal style ("|"): the only style that
// preserves a bash script unescaped, and the freshness script is one.
func scalarNode(v string) *yaml.Node {
	n := &yaml.Node{Kind: yaml.ScalarNode, Value: v}
	if strings.Contains(v, "\n") {
		n.Style = yaml.LiteralStyle
	}
	return n
}

// stringNode builds a scalar that must read back as a STRING, whatever it
// contains. Reserved for USER DATA: env keys AND values, egress hosts,
// freshness command arguments.
//
// The `!!str` tag makes the encoder quote only the values that would
// otherwise read back as something else — `~`, `null`, `true`, `8080`...
// Every value that is already a plain YAML string (`value`, a path,
// `github.com`, `bash`, `-c`, a literal block) renders byte-identical with or
// without the tag, which is why the golden file didn't move.
//
// Without it: a `TILDE: ~` read back as `""` and Differences reported "env
// changed" on EVERY attach although nothing had moved; worse, a null entry in
// a SEQUENCE (egress, freshness argv) simply vanished on reread. A permanent
// false warning teaches the user to stop reading it — including the day an
// egress really was narrowed.
func stringNode(v string) *yaml.Node {
	n := scalarNode(v)
	n.Tag = "!!str"
	return n
}

func sequenceNode(vals []string) *yaml.Node {
	n := &yaml.Node{Kind: yaml.SequenceNode}
	for _, v := range vals {
		n.Content = append(n.Content, stringNode(v))
	}
	return n
}

// mixinDir and mixinPath are the SOLE definition of where the mixin lives.
// Writing (WriteMixin) and reading (ReadMixin) must agree: if the two composed
// their path separately and diverged, ReadMixin would forever return
// os.ErrNotExist, and den would report "unverifiable drift" forever, for
// EVERY sandbox, without anything actually failing. Locked by
// TestReadMixinRereadsWhatWriteMixinWrote.
func mixinDir(denHome, sandboxName string) string {
	return filepath.Join(denHome, "cache", "mixins", sandboxName)
}

func mixinPath(denHome, sandboxName string) string {
	return filepath.Join(mixinDir(denHome, sandboxName), "spec.yaml")
}

// WriteMixin materializes the mixin under <denHome>/cache/mixins/<sandbox>/
// and returns the DIRECTORY — what `sbx create --kit` expects.
//
// Under cache/, not a mktemp: cache/ is declared reconstructible by spec §3,
// and a mixin that evaporates makes a failed boot undebuggable.
//
// The file describes what a VM received at its `sbx create`, not the current
// configuration: Spawn only calls WriteMixin on the create branch, and later
// uses it as a REFERENCE to detect configuration drift under a live sandbox
// (see ReadMixin and Differences). Rewriting it on every pass would destroy
// that reference — locked by TestSpawnDoesNotRewriteTheMixinOfALiveSandbox, in
// internal/spawn.
//
// Corollary: the file outlives the sandbox (den doesn't purge cache/), and a
// `sbx rm` followed by a new spawn replaces it.
//
// Restrictive permissions (0700/0600): spec.yaml carries
// environment.variables, i.e. the merged agent ∪ nest env — free-form user
// env, where an API key or a credentialed URI naturally ends up. Nothing
// justifies making it readable by every account on the machine.
//
// DELIBERATE choice, to confirm on the first real boot: `sbx` isn't
// installable here, so nobody has verified it reads the --kit under the
// calling uid. If it read it under a different, non-root uid, 0600 would
// break the boot — but loudly and immediately (permission denied on the first
// `create`), whereas a world-readable secret never signals itself. root, for
// its part, bypasses permissions anyway.
func WriteMixin(denHome, sandboxName string, m Mixin) (string, error) {
	// The guard lives here, not with the caller: this package turns a name into
	// a host path — both WriteMixin and ReadMixin, both exported, via the same
	// mixinPath — and "caller's responsibility" is a contract written nowhere.
	// sbx.SplitName is deliberately TOTAL and validates nothing (it also serves
	// sandboxes created outside den), and filepath.Join CLEANS a ".." into a
	// real traversal instead of rejecting it.
	//
	// Defense in depth: Spawn already refuses these names upstream, via
	// sbx.SandboxName. No PRODUCTION call path reaches this guard today, but
	// mixin_test.go's hostile-name cases do.
	if err := sbx.ValidateSandboxName(sandboxName); err != nil {
		return "", fmt.Errorf("writing mixin: %w", err)
	}
	dir := mixinDir(denHome, sandboxName)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", fmt.Errorf("creating %s: %w", dir, err)
	}
	content, err := RenderMixin(m)
	if err != nil {
		return "", err
	}
	path := mixinPath(denHome, sandboxName)
	if err := os.WriteFile(path, content, 0o600); err != nil {
		return "", fmt.Errorf("writing %s: %w", path, err)
	}
	return dir, nil
}
