package nest

import (
	"fmt"
	"maps"
	"path/filepath"
	"slices"
	"strings"

	"github.com/PillowPillow/den/internal/config"
)

// Options carries the overrides coming from CLI flags (the cascade's last level).
type Options struct {
	Agent   string   // --agent
	Without []string // --without
	Only    []string // --only
	// Repos are the repositories given as positionals on the command line, raw:
	// tilde unexpanded, possibly relative. They are additive to the nest's
	// `repos:`, and they are NOT addressable by --without/--only — a repo typed
	// by hand is removed by not typing it.
	Repos []string
	// Cwd resolves the relative entries of Repos. A parameter, not an
	// os.Getwd() inside this package: the resolution stays pure, so `den
	// scratch .` is assertable without a test having to chdir, and the one
	// system call lives with the other world access in internal/spawn.
	Cwd string
}

// Mount is a resolved `mounts:` entry, ready for the spawn argv and the mixin.
//
// It adds Key to config.Mount: the configuration key this entry CAME FROM,
// carried so a refusal can cite the line the user actually wrote. Without it,
// a missing ssh.dir would be reported as `mounts[0]` — a key absent from their
// config.yaml, because the entry was generated by the ssh.mode sugar.
type Mount struct {
	Host string
	Link string
	RO   bool
	Key  string // "mounts[N]" or "ssh.dir"
}

// resolveMounts flattens `mounts:` and the ssh.mode sugar into one list.
//
// `ssh.mode: mount` is SUGAR, not a parallel mechanism: it produces an ordinary
// mount and nothing downstream can tell the difference (except Key, for the
// message). That is what allows spawn.go to drop its `SSHMode == "mount"`
// special case — one mechanism, one place for a bug to live.
//
// Config mounts come FIRST and the sugar LAST, mirroring where ssh.dir sat in
// the workspace list before this change. The order is asserted by a test: it
// decides both the argv order and the link order.
func resolveMounts(g *config.Global) []Mount {
	out := make([]Mount, 0, len(g.Mounts)+1)
	for i, m := range g.Mounts {
		out = append(out, Mount{
			Host: m.Host,
			Link: m.Link,
			RO:   m.RO,
			Key:  fmt.Sprintf("mounts[%d]", i),
		})
	}
	if g.SSH.Mode == "mount" && g.SSH.Dir != "" {
		out = append(out, Mount{
			Host: g.SSH.Dir,
			// config owns the constant: config.Validate compares a user's
			// `mounts[].link` against the same string to refuse a collision
			// with this sugar. Two spellings would let one through.
			Link: config.SSHLinkTarget,
			// Never RO: ssh writes known_hosts, and a read-only mount turns
			// that into a failure far from its cause.
			Key: "ssh.dir",
		})
	}
	return out
}

// configDirToken is the marker substituted in the agent's env values.
//
// What it holds is a FACT: the HOST path of the agent's profile, the one den
// creates and that `sbx create` receives as a workspace.
//
// That this is useful INSIDE the VM is an unverified HYPOTHESIS — spec §14.1
// A11: that sbx mounts each workspace at the same absolute path in the VM as
// on the host. Project convention: anything about sbx's actual behavior is a
// hypothesis to document, never an assertion. Three real smokes have run
// against sbx since (the last on 2026-08-03, v0.35.0) and none aimed at this
// surface: A11 is open for want of a measurement, not for want of a binary.
//
// If it is false, CLAUDE_CONFIG_DIR points nowhere inside the VM and the
// agent starts from scratch on every spawn, silently — see A11 for what would
// falsify it at the first smoke test, and for what else depends on it (the
// `-w <host path>` of every attach).
const configDirToken = "{config_dir}"

// Resolved is a fully resolved nest: nothing left to compute downstream.
// internal/spawn consumes it as-is to build the mixin and the sbx create argv.
type Resolved struct {
	// DenHome is ALWAYS absolute (Resolve guarantees it): the generated mixin
	// is written under <DenHome>/cache/mixins/, and that path then goes as-is
	// to `sbx create`, where cwd is no longer guaranteed.
	DenHome string

	Nest  *Nest
	Stack *config.Stack

	AgentName      string
	Agent          config.Agent
	AgentConfigDir string // nest override if present, else the global registry

	// Env is the union READY TO APPLY: agent env ∪ nest env, nest winning,
	// {config_dir} substituted EVERYWHERE (both agent and nest). The
	// substitution is a cascade rule, not a display concern: it belongs here,
	// not in the mixin.
	Env map[string]string

	Egress []string // sorted union of baseline ∪ stack ∪ nest
	Repos  []Repo   // applied selection, declaration order

	SSHMode string
	// Mounts carries `ssh.dir` too, as the ssh.mode sugar (resolveMounts). No
	// SSHDir field beside it on purpose: spawn reads Mounts alone, and a second
	// field holding the same path would let a future "fix" edit the one nothing
	// mounts — it would compile, pass every test, and change nothing in the VM.
	Mounts         []Mount
	WorktreeLayout string
	WorktreeRoot   string
}

// mergeEnv applies the agent ← nest cascade and substitutes {config_dir} in
// BOTH sources: a nest may reassert an agent variable (e.g. CLAUDE_CONFIG_DIR)
// with the same token, and since the nest wins the cascade, an asymmetric
// substitution would let the literal token win instead.
// Always returns a non-nil map: consumers iterate without a guard.
func mergeEnv(agentEnv, nestEnv map[string]string, configDir string) map[string]string {
	out := make(map[string]string, len(agentEnv)+len(nestEnv))
	for k, v := range agentEnv {
		out[k] = strings.ReplaceAll(v, configDirToken, configDir)
	}
	for k, v := range nestEnv {
		out[k] = strings.ReplaceAll(v, configDirToken, configDir) // the nest is lower in the cascade: it wins
	}
	return out
}

// resolveAgent determines the active agent and its config_dir.
// Name priority: --agent flag > defaults.agent.
// config_dir priority: nest override for THIS agent > global registry.
func resolveAgent(g *config.Global, n *Nest, flagAgent string) (string, config.Agent, string, error) {
	name := flagAgent
	if name == "" {
		name = g.Defaults.Agent
	}

	a, ok := g.Agents[name]
	if !ok {
		available := slices.Sorted(maps.Keys(g.Agents))
		return "", config.Agent{}, "", fmt.Errorf(
			"unknown agent %q (declared agents: %v)", name, available)
	}

	configDir := a.ConfigDir
	if n != nil {
		if override, ok := n.Agents[name]; ok && override != "" {
			configDir = override
		}
	}
	return name, a, configDir, nil
}

// resolveRepoKeys fills the Path of every key-typed repo from the personal
// mapping. Refusal BEFORE any side effect, naming the exact file and line to
// add — and the clone command when the nest declared one (spec 2026-08-04
// §2.4). denHome locates config.yaml through GlobalPath: the message and the
// reader must never disagree on where that file lives.
//
// It runs on the SELECTED repos, after selectRepos, and the order is the
// whole point rather than an implementation detail. Resolving first made the
// unmapped-key refusal inescapable: `--without front-app` and `--only
// review-mgmt` both died on front-app before selection ever ran, so
// `optional:` meant something for a `path:` entry (a missing one could be
// dropped) and nothing for a `key:` one — the very axis the marker exists
// for, and the spec's own §2.4 example is exactly that nest. selectRepos
// keys off Repo.Name(), which returns the Key for a key-typed entry, so it
// needs no Path and the reorder costs nothing.
//
// What does NOT change is the doctrine: a key on a repo that is still
// SELECTED refuses, loudly, and den drops nothing on its own. The refusal
// only gains the escape when there IS one — see withoutClause.
func resolveRepoKeys(denHome string, mapping map[string]string, repos []Repo) ([]Repo, error) {
	out := slices.Clone(repos)
	for i, r := range out {
		if r.Key == "" {
			continue
		}
		path, ok := mapping[r.Key]
		if !ok {
			hint := ""
			if r.URL != "" {
				hint = fmt.Sprintf(" (clone: %s)", r.URL)
			}
			return nil, fmt.Errorf(
				"repo key %q is not mapped on this machine — add `%s: <local path>` under `repos:` "+
					"in %s%s%s", r.Key, r.Key, config.GlobalPath(denHome), hint, withoutClause(r))
		}
		out[i].Path = path
	}
	return out, nil
}

// withoutClause offers `--without <name>` — but only on an OPTIONAL repo,
// because only there does it work. A teammate who simply does not have the
// front-end repo needs to be told the escape rather than left to discover
// that the flag exists; a teammate missing a REQUIRED repo must not be sent
// to a flag selectRepos refuses outright ("is a required repo of this nest,
// it cannot be removed"), which would be a remedy naming a command that
// itself fails.
func withoutClause(r Repo) string {
	if !r.Optional {
		return ""
	}
	return fmt.Sprintf(
		" — or, since this repo is optional, leave it out of this spawn with `--without %s`", r.Name())
}

// Resolve applies the full global ← stack ← nest ← flags cascade.
//
// stacks is a config.Stacks rather than a map: the verdict "is this stack
// usable" distinguishes "unreadable" from "not declared", and that
// distinction belongs to config.Stacks.Get, its single source of truth. A map
// alone could only say "not found" — including for a stack that IS present
// but whose stack.yaml has a typo, sending the user to create a file that
// already exists.
func Resolve(denHome string, g *config.Global, stacks config.Stacks, n *Nest, o Options) (*Resolved, error) {
	if !filepath.IsAbs(denHome) {
		return nil, fmt.Errorf(
			"den home %q: not an absolute path (derived paths go as-is to "+
				"git worktree and sbx create, where cwd is no longer guaranteed)", denHome)
	}

	stackName := n.Stack
	if stackName == "" {
		stackName = g.Defaults.Stack
	}
	s, err := stacks.Get(stackName)
	if err != nil {
		// Nothing is appended after Get's error: it already locates what
		// needs locating (the stacks directory for "not found", the faulty
		// stack.yaml for "unreadable"). A suffix here would land behind
		// yaml.v3's MULTI-LINE diagnostic, where it would read as the
		// location of its last line.
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}

	agentName, agent, configDir, err := resolveAgent(g, n, o.Agent)
	if err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}

	// SELECTION FIRST, then key resolution — see resolveRepoKeys for why the
	// order is load-bearing: reversed, no flag could escape an unmapped key.
	repos, err := selectRepos(n.Repos, o.Without, o.Only)
	if err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}
	// Key resolution BEFORE the positionals are merged in, so the merged list
	// holds nothing but real paths: checkNoDuplicatePaths below compares them,
	// and an unresolved key (Path still empty) would silently sit out the very
	// comparison that catches `den backend ~/dev/review-mgmt` repeating a repo
	// the nest already maps to that same directory.
	repos, err = resolveRepoKeys(denHome, g.Repos, repos)
	if err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}
	adhoc, err := parseRepoArgs(o.Cwd, o.Repos)
	if err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}
	// Positionals FIRST, declared repos after: internal/spawn turns this list
	// into `sbx create`'s workspaces in order, and sbx.Sandbox.Workdir — the
	// directory the attached shell starts in — is Workspaces[0]. The gesture
	// "I am mounting X on the fly" means "I have come to work in X".
	//
	// This is the merge point of the whole feature, and the reason nothing
	// downstream needs a branch: from here on a repo given on the command line
	// IS a repo. It gets a worktree under -w, its common git dir mounted, its
	// place in the argv — by construction, not by repetition.
	repos = append(adhoc, repos...)
	// Re-checked on the MERGED list: LoadNest only ever saw the file. A
	// positional colliding with a declared basename makes --without, the
	// worktree path and the sbx positional ambiguous at once.
	if err := checkUniqueNames(repos, "spawn"); err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}
	// And only HERE, never in LoadNest: the basename worktree.Path derives the
	// worktree directory from is the one out of the personal mapping, which does
	// not exist until resolveRepoKeys has run just above. A team nest declaring
	// `key: api-v1` and `key: api-v2` is perfectly legal — it is this machine's
	// `repos:` pointing both at a directory named `api` that cannot be honored.
	if err := checkUniqueMountBasenames(repos, "spawn"); err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}

	return &Resolved{
		DenHome:        denHome,
		Nest:           n,
		Stack:          s,
		AgentName:      agentName,
		Agent:          agent,
		AgentConfigDir: configDir,
		Env:            mergeEnv(agent.Env, n.Env, configDir),
		Egress:         unionEgress(g.Egress, s.Egress, n.Egress),
		Repos:          repos,
		SSHMode:        g.SSH.Mode,
		Mounts:         resolveMounts(g),
		WorktreeLayout: g.WorktreeLayout,
		WorktreeRoot:   g.WorktreeRoot,
	}, nil
}
