package nest

import (
	"fmt"
	"maps"
	"path/filepath"
	"slices"
	"strings"

	"github.com/PillowPillow/den/internal/config"
)

// Options carries the overrides coming from CLI flags (the cascade's last level).
type Options struct {
	Agent   string   // --agent
	Without []string // --without
	Only    []string // --only
	// Repos are the repositories given behind --repo, raw: tilde unexpanded,
	// possibly relative. They are additive to the nest's `repos:`, and they are
	// NOT addressable by --without/--only — a repo typed by hand is removed by
	// not typing it.
	Repos []string
	// Resources is the cascade's LAST level for `resources:` — what a flag
	// says, over what the nest, the stack and config.yaml declare.
	//
	// No cobra flag fills it yet (issue #90 ships the cascade; the two-line
	// wiring on `den up`/`den run` is its own change, in internal/cli, which
	// this pass does not own). The level exists here because leaving it out
	// would put the flags' precedence in no test at all, and because a level
	// added later is a level whose order nothing ever asserted.
	Resources config.Resources
	// Cwd resolves the relative entries of Repos. A parameter, not an
	// os.Getwd() inside this package: the resolution stays pure, so `den
	// scratch .` is assertable without a test having to chdir, and the one
	// system call lives with the other world access in internal/spawn.
	Cwd string
	// TolerateUnmappedOptional is `den nest show`'s ALONE. internal/spawn must
	// never set it, and the asymmetry is the point: on a `select: prompt` nest an
	// unmapped optional `key:` is a normal state (the session did not ask for
	// that repo), but a SPAWN still has to refuse it, because the only way to
	// reach a spawn with an unmapped key is to have selected it. A dry-run has no
	// such moment: it resolves the whole declared nest, so the same key it must
	// merely REPORT would refuse the listing outright — the dry-run of the new
	// mode could not be run on the nests the mode exists for.
	//
	// Set, it moves those repos out of Resolved.Repos and into
	// Resolved.UnmappedOptional. Moves, not annotates in place: a Repo in
	// Resolved.Repos with an empty Path becomes an `sbx create` workspace
	// downstream, and that would compile, pass every test that leaves this field
	// false, and hand sbx a blank argument the day something else set it.
	//
	// It never covers a key the caller named on `--only`: see setAsideUnmapped.
	TolerateUnmappedOptional bool

	// RepoMapping is the mapping a `key:` resolves through, when the caller
	// has one of its own. nil — the local and legacy case — keeps
	// config.yaml.repos, so nothing changes for a den without manifested
	// sources.
	//
	// An EMPTY, non-nil map is NOT the same as nil, and the distinction is the
	// whole mechanism: a manifested source that maps nothing yet must refuse
	// its keys naming its own file, never resolve them through the personal
	// global mapping — a key like `api` means different repositories in
	// different sources, and one global answer would silently hand a spawn
	// the wrong repository (spec §6). source.Personal.ExpandedRepos always
	// returns a non-nil map for exactly this reason.
	//
	// A plain map, deliberately, and not a source object: internal/source
	// imports this package (decode.go), so the reverse edge would be a cycle.
	RepoMapping map[string]string
	// RepoMappingPath is the file an unmapped-key refusal must send the user
	// to. Read only when RepoMapping is non-nil; otherwise the message keeps
	// naming config.GlobalPath(denHome).
	RepoMappingPath string
}

// repoMapping returns the mapping to resolve `key:` entries through, and the
// file a refusal must name. ONE function, so the resolution and the message
// can never disagree about which file the user has to edit.
func (o Options) repoMapping(denHome string, g *config.Global) (map[string]string, string) {
	if o.RepoMapping == nil {
		return g.Repos, config.GlobalPath(denHome)
	}
	return o.RepoMapping, o.RepoMappingPath
}

// Mount is a resolved `mounts:` entry, ready for the spawn argv and the mixin.
//
// It adds Key to config.Mount: the configuration key this entry CAME FROM,
// carried so a refusal can cite the line the user actually wrote. Without it,
// a missing ssh.dir would be reported as `mounts[0]` — a key absent from their
// config.yaml, because the entry was generated by the ssh.mode sugar.
type Mount struct {
	Host string
	Link string
	RO   bool
	Key  string // "mounts[N]" or "ssh.dir"
}

// SSHDirKey is the Key of the Mount that `ssh.mode: mount` desugars into: the
// configuration key a message must name for that entry, since it appears in no
// `mounts:` block of the user's config.yaml.
const SSHDirKey = "ssh.dir"

// resolveMounts flattens `mounts:` and the ssh.mode sugar into one list.
//
// `ssh.mode: mount` is SUGAR, not a parallel mechanism: it produces an ordinary
// mount and nothing downstream can tell the difference (except Key, for the
// message). That is what allows spawn.go to drop its `SSHMode == "mount"`
// special case — one mechanism, one place for a bug to live.
//
// Config mounts come FIRST and the sugar LAST, mirroring where ssh.dir sat in
// the workspace list before this change. The order is asserted by a test: it
// decides both the argv order and the link order.
func resolveMounts(g *config.Global) []Mount {
	out := make([]Mount, 0, len(g.Mounts)+1)
	for i, m := range g.Mounts {
		out = append(out, Mount{
			Host: m.Host,
			Link: m.Link,
			RO:   m.RO,
			Key:  fmt.Sprintf("mounts[%d]", i),
		})
	}
	if g.SSH.Mode == "mount" && g.SSH.Dir != "" {
		out = append(out, Mount{
			Host: g.SSH.Dir,
			// SSHDirKey, not the literal: spawn's warning header reads the Key
			// back to decide which configuration key to name, and a second
			// spelling would send a `ssh.mode: mount` user to a `mounts:` block
			// their config.yaml does not contain. Same rule as Link just below.
			// config owns the constant: config.Validate compares a user's
			// `mounts[].link` against the same string to refuse a collision
			// with this sugar. Two spellings would let one through.
			Link: config.SSHLinkTarget,
			// Never RO: ssh writes known_hosts, and a read-only mount turns
			// that into a failure far from its cause.
			Key: SSHDirKey,
		})
	}
	return out
}

// configDirToken is the marker substituted in the agent's env values.
//
// What it holds is a FACT: the HOST path of the agent's profile, the one den
// creates and that `sbx create` receives as a workspace.
//
// That this is useful INSIDE the VM is an unverified HYPOTHESIS — spec §14.1
// A11: that sbx mounts each workspace at the same absolute path in the VM as
// on the host. Project convention: anything about sbx's actual behavior is a
// hypothesis to document, never an assertion. Three real smokes have run
// against sbx since (the last on 2026-08-03, v0.35.0) and none aimed at this
// surface: A11 is open for want of a measurement, not for want of a binary.
//
// If it is false, CLAUDE_CONFIG_DIR points nowhere inside the VM and the
// agent starts from scratch on every spawn, silently — see A11 for what would
// falsify it at the first smoke test, and for what else depends on it (the
// `-w <host path>` of every attach).
const configDirToken = "{config_dir}"

// Resolved is a fully resolved nest: nothing left to compute downstream.
// internal/spawn consumes it as-is to build the mixin and the sbx create argv.
type Resolved struct {
	// DenHome is ALWAYS absolute (Resolve guarantees it): the generated mixin
	// is written under <DenHome>/cache/mixins/, and that path then goes as-is
	// to `sbx create`, where cwd is no longer guaranteed.
	DenHome string

	Nest  *Nest
	Stack *config.Stack

	AgentName      string
	Agent          config.Agent
	AgentConfigDir string // nest override if present, else the global registry

	// Env is the union READY TO APPLY: agent env ∪ nest env, nest winning,
	// {config_dir} substituted EVERYWHERE (both agent and nest). The
	// substitution is a cascade rule, not a display concern: it belongs here,
	// not in the mixin.
	Env map[string]string

	Egress []string // sorted union of baseline ∪ stack ∪ nest
	Repos  []Repo   // applied selection, declaration order
	// UnmappedOptional holds the optional `key:` repos this machine maps nowhere,
	// set aside instead of refused — always empty unless the caller asked for
	// that (Options.TolerateUnmappedOptional), so a spawn cannot grow a silent
	// hole in its mounts. Each entry is resolveRepoKeys' own refusal, unsent: the
	// reason it would have refused, with the file to edit and the clone URL, so a
	// listing renders the SAME sentence a spawn would have printed.
	//
	// A SEPARATE field rather than a marker on the Repos entries, and this is the
	// regression it exists to prevent: internal/spawn turns Repos into `sbx
	// create`'s workspaces, one argument per entry, and these repos have no Path
	// on this machine. Left in Repos and merely flagged, the first reader that
	// forgot the flag would hand sbx a blank workspace — it would compile, it
	// would pass every test that leaves TolerateUnmappedOptional false, and it
	// would break in the VM, far from here. Out of Repos, there is nothing to
	// forget.
	UnmappedOptional []*UnmappedRepoKeyError

	// Resources is the microVM's size, fully merged: internal/spawn hands it to
	// sbx.EnvFile, which writes no `cpus:` key when CPUs is nil and no
	// `memory:` key when Memory is empty. Already validated — Resolve refuses
	// an unusable value rather than passing it on, so nothing downstream needs
	// to ask again.
	Resources config.Resources

	SSHMode string
	// Mounts carries `ssh.dir` too, as the ssh.mode sugar (resolveMounts). No
	// SSHDir field beside it on purpose: spawn reads Mounts alone, and a second
	// field holding the same path would let a future "fix" edit the one nothing
	// mounts — it would compile, pass every test, and change nothing in the VM.
	Mounts         []Mount
	WorktreeLayout string
	WorktreeRoot   string
}

// mergeEnv applies the agent ← nest cascade and substitutes {config_dir} in
// BOTH sources: a nest may reassert an agent variable (e.g. CLAUDE_CONFIG_DIR)
// with the same token, and since the nest wins the cascade, an asymmetric
// substitution would let the literal token win instead.
// Always returns a non-nil map: consumers iterate without a guard.
func mergeEnv(agentEnv, nestEnv map[string]string, configDir string) map[string]string {
	out := make(map[string]string, len(agentEnv)+len(nestEnv))
	for k, v := range agentEnv {
		out[k] = strings.ReplaceAll(v, configDirToken, configDir)
	}
	for k, v := range nestEnv {
		out[k] = strings.ReplaceAll(v, configDirToken, configDir) // the nest is lower in the cascade: it wins
	}
	return out
}

// resolveAgent determines the active agent and its config_dir.
// Name priority: --agent flag > defaults.agent.
// config_dir priority: nest override for THIS agent > global registry.
func resolveAgent(g *config.Global, n *Nest, flagAgent string) (string, config.Agent, string, error) {
	name := flagAgent
	if name == "" {
		name = g.Defaults.Agent
	}

	a, ok := g.Agents[name]
	if !ok {
		available := slices.Sorted(maps.Keys(g.Agents))
		return "", config.Agent{}, "", fmt.Errorf(
			"unknown agent %q (declared agents: %v)", name, available)
	}

	configDir := a.ConfigDir
	if n != nil {
		if override, ok := n.Agents[name]; ok && override != "" {
			configDir = override
		}
	}
	return name, a, configDir, nil
}

// UnmappedRepoKeyError is resolveRepoKeys' refusal, given a TYPE so a caller can
// act on the verdict instead of matching its text — the same reason
// config.UnreadableStackError has one.
//
// internal/spawn is the caller, and what it knows that this package must not is
// LIVENESS: on a sandbox that is already running, its mounts are frozen at its
// creation, so mapping the key in config.yaml adds nothing to that VM and the
// remedy this message names is the wrong one there. Resolve stays pure and
// learns nothing about sandboxes; the verdict stays its own, and only becomes
// inspectable with errors.As.
//
// The fields are the message's own parts rather than a pre-formatted string:
// spawn needs Key to name the flag's argument, and one source for the text is
// what keeps README's quoted copy of it honest.
type UnmappedRepoKeyError struct {
	Key      string // the `key:` no personal `repos:` entry carries
	Optional bool   // the nest's `optional:` marker — an escape exists only there
	// Prompts is the nest's `select: prompt` mode. It is here because the escape
	// this message offers is not the same flag in both modes: internal/spawn
	// REFUSES `--without` on a prompting nest (it has no default selection to
	// subtract from), so offering it here would name a command den rejects. The
	// mode is this package's own — Nest.Select, PromptsForRepos — so nothing is
	// learnt about sandboxes to know it.
	Prompts    bool
	URL        string // the nest's `url:`, when it declared one: what to clone
	ConfigPath string // the personal config.yaml this machine would map it in
}

// Error keeps, word for word, the message resolveRepoKeys built inline before
// the type existed — README quotes its opening and internal/spawn asserts
// substrings of it. Only the escape clause moved, and only on a prompting nest,
// where the flag it used to offer is now refused.
func (e *UnmappedRepoKeyError) Error() string {
	return e.Remedy() + e.withoutClause()
}

// Remedy is the message WITHOUT its escape clause: the fact and the fix, which
// are true wherever this key is met.
//
// Split out for `den nest show`, which lists the keys it set aside rather than
// refusing on them (Resolved.UnmappedOptional). There the escape clause would be
// an answer to a question nobody asked — the repo is ALREADY left out of that
// listing — while the fact and the fix are exactly what the reader came for.
// Rebuilding a shorter sentence at the listing site instead would be a second
// dialect for one remedy, which is the defect this type was extracted to end.
func (e *UnmappedRepoKeyError) Remedy() string {
	hint := ""
	if e.URL != "" {
		hint = fmt.Sprintf(" (clone: %s)", e.URL)
	}
	return fmt.Sprintf(
		"repo key %q is not mapped on this machine — add `%s: <local path>` under `repos:` "+
			"in %s%s", e.Key, e.Key, e.ConfigPath, hint)
}

// withoutClause offers the escape — but only on an OPTIONAL repo, because only
// there is there one. A teammate who simply does not have the front-end repo
// needs to be told it rather than left to discover that the flag exists; a
// teammate missing a REQUIRED repo must not be sent to a flag selectRepos
// refuses outright ("is a required repo of this nest, it cannot be removed"),
// which would be a remedy naming a command that itself fails.
//
// Which flag it names follows the nest's mode, for exactly that reason one step
// further: on a `select: prompt` nest `--without` is the command that fails, so
// the escape there is `--only`, the spelling that states the set outright.
//
// Key, not Repo.Name(): the two are the same string for a key-typed repo
// (Name() returns the Key), and this error only ever describes one.
func (e *UnmappedRepoKeyError) withoutClause() string {
	if !e.Optional {
		return ""
	}
	if e.Prompts {
		return " — or, since this repo is optional, leave it out of this spawn by naming the " +
			"repos you do want with `--only repo,...` (this nest selects its repos at spawn " +
			"time, so `--without` is refused on it)"
	}
	return fmt.Sprintf(
		" — or, since this repo is optional, leave it out of this spawn with `--without %s`", e.Key)
}

// setAsideUnmapped splits the OPTIONAL key-typed repos this machine maps nowhere
// out of the selection, and returns them as the refusals resolveRepoKeys would
// have raised on them. It is what Options.TolerateUnmappedOptional turns on, and
// Resolve calls it only on a `select: prompt` nest.
//
// Two exclusions, and both are the whole point:
//
//   - REQUIRED repos are never set aside. `select: prompt` governs the optional
//     repos — a required one is mounted by every spawn of the nest, so an
//     unmapped key there is a real fault on a prompting nest exactly as it is on
//     any other, and it must still refuse.
//   - a repo the caller named on `--only` is never set aside. `--only crm` is a
//     user asking for crm by hand; a dry-run that quietly listed it as "not
//     mapped" and exited 0, where the spawn of that same command line refuses,
//     would be a dry-run disagreeing with the run — the divergence this whole
//     surface exists to close. Naming it is what makes the refusal theirs to see.
//
// only is matched on Repo.Name(), the same identity selectRepos addresses a repo
// by (the Key for a key-typed entry), so the two cannot drift apart.
// configPath is the file the returned refusals name — config.yaml for a local
// nest, the source's own source-config/<name>.yaml for a manifested one. It is
// passed in rather than derived here: only Resolve knows which mapping it
// selected, and a message naming the other file would send the user to edit a
// key that is not there.
func setAsideUnmapped(configPath string, mapping map[string]string, repos []Repo,
	only []string) (kept []Repo, aside []*UnmappedRepoKeyError) {

	kept = make([]Repo, 0, len(repos))
	for _, r := range repos {
		if r.Key == "" || !r.Optional || slices.Contains(only, r.Name()) {
			kept = append(kept, r)
			continue
		}
		if _, ok := mapping[r.Key]; ok {
			kept = append(kept, r)
			continue
		}
		aside = append(aside, &UnmappedRepoKeyError{
			Key:        r.Key,
			Optional:   r.Optional,
			Prompts:    true, // the only mode Resolve calls this in
			URL:        r.URL,
			ConfigPath: configPath,
		})
	}
	return kept, aside
}

// resolveRepoKeys fills the Path of every key-typed repo from the personal
// mapping. Refusal BEFORE any side effect, naming the exact file and line to
// add — and the clone command when the nest declared one (spec 2026-08-04
// §2.4). denHome locates config.yaml through GlobalPath: the message and the
// reader must never disagree on where that file lives.
//
// It runs on the SELECTED repos, after selectRepos, and the order is the
// whole point rather than an implementation detail. Resolving first made the
// unmapped-key refusal inescapable: `--without front-app` and `--only
// review-mgmt` both died on front-app before selection ever ran, so
// `optional:` meant something for a `path:` entry (a missing one could be
// dropped) and nothing for a `key:` one — the very axis the marker exists
// for, and the spec's own §2.4 example is exactly that nest. selectRepos
// keys off Repo.Name(), which returns the Key for a key-typed entry, so it
// needs no Path and the reorder costs nothing.
//
// What does NOT change is the doctrine: a key on a repo that is still
// SELECTED refuses, loudly, and den drops nothing on its own. The refusal
// only gains the escape when there IS one — see withoutClause.
func resolveRepoKeys(configPath string, mapping map[string]string, repos []Repo, prompts bool) ([]Repo, error) {
	out := slices.Clone(repos)
	for i, r := range out {
		if r.Key == "" {
			continue
		}
		path, ok := mapping[r.Key]
		if !ok {
			return nil, &UnmappedRepoKeyError{
				Key:        r.Key,
				Optional:   r.Optional,
				Prompts:    prompts,
				URL:        r.URL,
				ConfigPath: configPath,
			}
		}
		out[i].Path = path
	}
	return out, nil
}

// Resolve applies the full global ← stack ← nest ← flags cascade.
//
// stacks is a config.Stacks rather than a map: the verdict "is this stack
// usable" distinguishes "unreadable" from "not declared", and that
// distinction belongs to config.Stacks.Get, its single source of truth. A map
// alone could only say "not found" — including for a stack that IS present
// but whose stack.yaml has a typo, sending the user to create a file that
// already exists.
func Resolve(denHome string, g *config.Global, stacks config.Stacks, n *Nest, o Options) (*Resolved, error) {
	if !filepath.IsAbs(denHome) {
		return nil, fmt.Errorf(
			"den home %q: not an absolute path (derived paths go as-is to "+
				"git worktree and the emitted .sbxenv.yaml, where cwd is no longer guaranteed)",
			denHome)
	}

	// TrimSpace on both halves, not `== ""`: since defaults.stack became
	// optional (config.Validate no longer requires it — see the comment at its
	// removed check), nothing upstream refuses a blank spelling anymore, and a
	// `stack: "   "` would otherwise be carried to stacks.Get as a real name.
	stackName := strings.TrimSpace(n.Stack)
	if stackName == "" {
		stackName = strings.TrimSpace(g.Defaults.Stack)
	}
	// Neither half of the cascade named a stack. Refused HERE rather than at
	// load: config.Validate sees only the global default, and the nest's own
	// `stack:` is what makes an absent default legitimate — a source-aware den
	// home has no default at all and every nest it spawns declares its own.
	//
	// The empty name must never reach stacks.Get: its verdict would be
	// `stack "" not found (declared stacks: [...])`, which reads as an
	// invitation to create a stack whose name is the empty string — the same
	// fault the blank-field discipline in config.Validate exists to prevent.
	// Both files are named because the fix belongs to exactly one of them and
	// the user cannot tell which from the outside.
	if stackName == "" {
		return nil, fmt.Errorf(
			"nest %q: no stack is configured — add `stack:` to %s, or set `defaults.stack` in %s",
			n.Name, FilePath(denHome, n.Name), config.GlobalPath(denHome))
	}
	s, err := stacks.Get(stackName)
	if err != nil {
		// Nothing is appended after Get's error: it already locates what
		// needs locating (the stacks directory for "not found", the faulty
		// stack.yaml for "unreadable"). A suffix here would land behind
		// yaml.v3's MULTI-LINE diagnostic, where it would read as the
		// location of its last line.
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}

	agentName, agent, configDir, err := resolveAgent(g, n, o.Agent)
	if err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}

	// Before any repo work, and long before the spawn's first side effect: a
	// `resources:` sbx would reject is refusable from the configuration alone,
	// which spec §6 places ahead of everything that creates a worktree.
	resources, err := resolveResources(denHome, g, s, n, o)
	if err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}

	// Which mapping resolves this nest's `key:` entries, and which file a
	// refusal about them names. Read ONCE, here, and passed down: the two
	// consumers below (the dry-run's set-aside and the resolution proper) must
	// never answer that question apart.
	mapping, mappingPath := o.repoMapping(denHome, g)

	// SELECTION FIRST, then key resolution — see resolveRepoKeys for why the
	// order is load-bearing: reversed, no flag could escape an unmapped key.
	repos, err := selectRepos(n.Repos, o.Without, o.Only)
	if err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}
	// The dry-run's tolerance, between the selection and the key resolution:
	// after selectRepos, because a repo `--without` already dropped is not
	// "unmapped", it is absent; before resolveRepoKeys, because that function's
	// job is to refuse precisely what this one has just set aside. Guarded on the
	// MODE as well as on the option — an unmapped key on a `select: all` nest is
	// a fault whoever is asking, and the listing of such a nest must keep
	// refusing (Options.TolerateUnmappedOptional).
	var unmappedOptional []*UnmappedRepoKeyError
	if o.TolerateUnmappedOptional && n.PromptsForRepos() {
		repos, unmappedOptional = setAsideUnmapped(mappingPath, mapping, repos, o.Only)
	}
	// Key resolution BEFORE the positionals are merged in, so the merged list
	// holds nothing but real paths: checkNoDuplicatePaths below compares them,
	// and an unresolved key (Path still empty) would silently sit out the very
	// comparison that catches `den backend ~/dev/review-mgmt` repeating a repo
	// the nest already maps to that same directory.
	repos, err = resolveRepoKeys(mappingPath, mapping, repos, n.PromptsForRepos())
	if err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}
	adhoc, err := parseRepoArgs(o.Cwd, o.Repos)
	if err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}
	// Positionals FIRST, declared repos after: internal/spawn turns this list
	// into `sbx create`'s workspaces in order, and sbx.Sandbox.Workdir — the
	// directory the attached shell starts in — is Workspaces[0]. The gesture
	// "I am mounting X on the fly" means "I have come to work in X".
	//
	// This is the merge point of the whole feature, and the reason nothing
	// downstream needs a branch: from here on a repo given on the command line
	// IS a repo. It gets a worktree under -w, its common git dir mounted, its
	// place in the argv — by construction, not by repetition.
	repos = append(adhoc, repos...)
	// Re-checked on the MERGED list: LoadNest only ever saw the file. A
	// positional colliding with a declared basename makes --without, the
	// worktree path and the sbx positional ambiguous at once.
	if err := checkUniqueNames(repos, "spawn"); err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}
	// And only HERE, never in LoadNest: the basename worktree.Path derives the
	// worktree directory from is the one out of the personal mapping, which does
	// not exist until resolveRepoKeys has run just above. A team nest declaring
	// `key: api-v1` and `key: api-v2` is perfectly legal — it is this machine's
	// `repos:` pointing both at a directory named `api` that cannot be honored.
	if err := checkUniqueMountBasenames(repos, "spawn"); err != nil {
		return nil, fmt.Errorf("nest %q: %w", n.Name, err)
	}

	return &Resolved{
		DenHome:          denHome,
		Nest:             n,
		Stack:            s,
		AgentName:        agentName,
		Agent:            agent,
		AgentConfigDir:   configDir,
		Env:              mergeEnv(agent.Env, n.Env, configDir),
		Egress:           unionEgress(g.Egress, s.Egress, n.Egress),
		Repos:            repos,
		UnmappedOptional: unmappedOptional,
		Resources:        resources,
		SSHMode:          g.SSH.Mode,
		Mounts:           resolveMounts(g),
		WorktreeLayout:   g.WorktreeLayout,
		WorktreeRoot:     g.WorktreeRoot,
	}, nil
}
